#!/usr/bin/env bash

VERSION='1.0.0'

: ${PACKAGE_JSON:="./package.json"}
: ${README_MD:="./README.md"}

# Document available command line options. This function
# simply outputs script's SYNOPSIS to the user terminal.
__help() {
cat << EOS
Usage:
    $(basename ${0}) [options]

    THIS SCRIPT SHOULD BE INVOKED VIA "npm run release"

    Upgrade static dependancies then build and test the extension.

        Options                 All options are optional and
        -------                 can be supplied in any order.

        -l --log=<path>         Redirect all output to a file
        -q --quiet              Suppress output of the script
        -? --help               Display this help message
        --version               Script and BASH version info

    <> - required parameters    [] - optional parameters
EOS
}

# This function is executed after processing all supplied
# options but before looking at the script's arguments.
__init() {
    INITIAL_WORKING_DIR="$pwd"
    cd $(dirname ${0})/..
}

# This function is called when the script receives an EXIT pseudo-signal. It
# simulates a common destructor behaviour inside BASH scripts. It allows this
# script to release and clean up resources upon termination.
__exit() {
    cd ${INITIAL_WORKING_DIR}
}

# Insure the presence of OPTARG in the current scope. If OPTARG is missing then
# display help message via __help and exit with an error code.
require_OPTARG() {
    if [[ -z ${OPTARG} ]]; then
        echo "${0}: option requires an argument -- ${OPTKEY}" >&2
        __help
        exit 11
    fi
}

# Test if a given value means NO.
is_false() {
    local value="$(echo ${1} | tr [:upper:] [:lower:])"

    if [[ -z ${value} || ${value} =~ ^0|n|no|false|none|null|nil$ ]]; then
        return 0
    fi

    return 1
}

# Test if a given value means YES.
is_true() {
    if is_false ${1}; then
        return 1
    fi

    return 0
}

# By default BASH does not provide support for long options. However, we can
# trick it into doing so by defining '-:' as part of the optspec.
while getopts "l:q?-:" OPTKEY; do

    if [[ "${OPTKEY}" = '-' ]]; then
        OPTKEY=`echo ${OPTARG} | sed -e 's/=.*//'`
        OPTARG=`echo ${OPTARG} | sed -e "s/^${OPTKEY}=\{0,1\}//"`
    fi

    case ${OPTKEY} in
        'l'|'log')
            require_OPTARG
            mkdir -p $(dirname ${OPTARG})
            exec > ${OPTARG} 2>&1
            ;;
        'q'|'quiet')
            exec > /dev/null
            ;;
        'version')
            echo "Shell script $0 version ${VERSION}"
            echo `bash --version | head -n 1`
            exit
            ;;
        '?'|'help')
            __help
            exit
            ;;
        *)
            if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
                echo "${0}: illegal option -- ${OPTKEY}" >&2
                __help
                exit 10
            fi
            ;;
    esac
done

# Clear all options and reset the command line argument count
shift $(( OPTIND -1 ))

# Check for an option-terminator string
if [[ "${1}" == "--" ]]; then
    shift
fi

# Initialise script destructor
trap __exit EXIT
__init

# Process all supplied arguments
if [[ -n ${@} ]]; then
  echo "${0}: illegal argument -- ${@}" >&2
  __help
  exit 30
fi

echo -e "\n** Starting release process **\n"

RELEASE_VERSION=$(node -pe "require('${PACKAGE_JSON}').version")
read -p "Update version number? [${RELEASE_VERSION}] " -t 300 NEW_RELEASE_VERSION
if [[ -n "${NEW_RELEASE_VERSION}" && "${RELEASE_VERSION}" != "${NEW_RELEASE_VERSION}" ]]; then
    node -pe "package = require('${PACKAGE_JSON}'); \
        package.version = '${NEW_RELEASE_VERSION}'; \
        content = JSON.stringify(package, null, 2); \
        require('fs').writeFileSync('${PACKAGE_JSON}', content)" > /dev/null
    sed -E \
        "s/^(\*\*Version:\*\* )[[:digit:]]+.[[:digit:]]+.[[:digit:]]+/\1${NEW_RELEASE_VERSION}/" \
        ${README_MD}
fi

git submodule update --recursive --remote
npm install

echo
npm outdated
echo
read -p "Update outdated packages? [y/N] " -t 300 RUN_NPM_UPDATE
if is_true ${RUN_NPM_UPDATE}; then
    npm update
    echo
    npm outdated
    echo
fi

npm test
